# Generated by Django 5.2.11 on 2026-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
