# Generated by Django 5.2.11 on 2026-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatfile',
            name='file',
        ),
        migrations.AddField(
            model_name='chatfile',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatfile',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatfile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
