# Generated by Django 5.2.11 on 2026-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatfile_file_chatfile_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
